eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#System properties override config server (default & safer)
spring:
  cloud:
    config:
      override-system-properties: false
