server:
  port: 9092

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookdb?sslmode=disable&connectTimeout=10&socketTimeout=30&ApplicationName=book-service
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect