spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_db
    username: root
    password: test@123
    driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL8Dialect
  # Add eureka configuration
  #eureka:
  #  client:
  #    service-url:
  #      defaultZone: http://localhost:8761/eureka/
  #    register-with-eureka: true
  #    fetch-registry: true
  #    registry-fetch-interval-seconds: 30
  #  instance:
  #    prefer-ip-address: true
  #    lease-renewal-interval-in-seconds: 30
  #    lease-expiration-duration-in-seconds: 90
  #    instance-id: ${spring.application.name}:${server.port}

  # Server configuration
server:
  port: 9000

#server:
#  port: 9092
#
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/bookdb?sslmode=disable&connectTimeout=10&socketTimeout=30&ApplicationName=book-service
#    username: test
#    password: test
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect