services:
  postgresql:
    image: postgres:15
    container_name: postgres-container
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: book
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - backend-services

  # PGAdmin UI for postgres
  pgadmin:
    image: dpage/pgadmin4
    container_name: ms_pgadmin_ui
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - backend-services
    depends_on:
      - postgresql

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
    volumes:
      - mongodata:/data/db
    networks:
      - backend-services

  # mongo-express UI for mongodb
  mongo-express:
    image: mongo-express
    container_name: mongo_express_ui
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: test
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - backend-services
    restart: always
    depends_on:
      - mongodb

  # Keycloak Server (using shared PostgreSQL)
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgresql:5432/keycloakdb
      KC_DB_USERNAME: test
      KC_DB_PASSWORD: test
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
    ports:
      - "8180:8080"
    depends_on:
      - postgresql
    networks:
      - backend-services

networks:
  backend-services:
    driver: bridge

volumes:
  pgdata:
  mongodata:
  pgadmin:
