spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/CodeNetJava/Library-Application.git
          default-label: feature/book-issue
          search-paths: services/config-server/src/main/resources/configurations

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

server:
  port: 8888
